import { Component, OnInit } from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IonicModule } from '@ionic/angular';
import { addIcons } from 'ionicons';
import { chevronForward } from 'ionicons/icons';

@Component({
  selector: 'app-stock-establishment',
  templateUrl: './stock-establishment.page.html',
  styleUrls: ['./stock-establishment.page.scss'],
  standalone: true,
  imports: [IonicModule, CommonModule, FormsModule]
})
export class StockEstablishmentPage implements OnInit {

  data: any = [
    {
      swc_dash_vprd_siga: '583800750001',
      swc_dash_vprd_sismed: '02884',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'DIMENHIDRINATO 50 MG INY 5 ML',
      TipoMI: 'M',
      PrecioU: 0.27,
      consumo: 1,
      stock: 140,
      fila: '33',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: 'SN0000000002',
      swc_dash_vprd_sismed: '',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'DOLUTEGRAVIR 50 mg TAB',
      TipoMI: 'M',
      PrecioU: 121.965661,
      consumo: 25.431654,
      stock: 36918,
      fila: '34',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583000490001',
      swc_dash_vprd_sismed: '03010',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'DOPAMINA CLORHIDRATO 40 MG/ML INY 5 ML',
      TipoMI: 'M',
      PrecioU: 2.3999,
      consumo: 0,
      stock: 2,
      fila: '35',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583400020001',
      swc_dash_vprd_sismed: '03013',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'DORZOLAMIDA 5 ML 20 MG/ML SOL',
      TipoMI: 'M',
      PrecioU: 8.3699,
      consumo: 36,
      stock: 969,
      fila: '36',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '581100050001',
      swc_dash_vprd_sismed: '03018',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'DOXICICLINA 100 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.12,
      consumo: 0,
      stock: 823,
      fila: '37',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580300190002',
      swc_dash_vprd_sismed: '03097',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'EPINEFRINA (COMO CLORHIDRATO O TARTRATO) 1 MG INY 1 ML',
      TipoMI: 'M',
      PrecioU: 0.68,
      consumo: 1,
      stock: 62,
      fila: '38',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '495701290012',
      swc_dash_vprd_sismed: '10929',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'EQUIPO DE VENOCLISIS ',
      TipoMI: 'I',
      PrecioU: 0.66,
      consumo: 9,
      stock: 119,
      fila: '39',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583000510001',
      swc_dash_vprd_sismed: '03317',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'ETILEFRINA 10 MG INY 1 ML',
      TipoMI: 'M',
      PrecioU: 12.23,
      consumo: 1,
      stock: 12,
      fila: '40',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400310014',
      swc_dash_vprd_sismed: '03423',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'FENILEFRINA 5 ML 1 MG/100 ML SOL',
      TipoMI: 'M',
      PrecioU: 19.19,
      consumo: 3,
      stock: 18,
      fila: '41',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580100230001',
      swc_dash_vprd_sismed: '03501',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'FENTANILO 50 UG/ML INY 10 ML',
      TipoMI: 'M',
      PrecioU: 3.49,
      consumo: 1,
      stock: 30,
      fila: '42',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '581800100005',
      swc_dash_vprd_sismed: '03595',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'FLUCONAZOL 150 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.33,
      consumo: 0,
      stock: 183,
      fila: '43',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583700010004',
      swc_dash_vprd_sismed: '03710',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'FUROSEMIDA 10 MG/ML INY 2 ML',
      TipoMI: 'M',
      PrecioU: 0.36,
      consumo: 0,
      stock: 10,
      fila: '44',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400590006',
      swc_dash_vprd_sismed: '18895',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'GENTAMICINA 3 MG/ML SOL OFT 5 ML',
      TipoMI: 'M',
      PrecioU: 2.81,
      consumo: 0,
      stock: 6,
      fila: '45',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580900040002',
      swc_dash_vprd_sismed: '03751',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'GENTAMICINA SULFATO 40 MG/ML INY 2 ML',
      TipoMI: 'M',
      PrecioU: 0.4,
      consumo: 0,
      stock: 4,
      fila: '46',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '587100010007',
      swc_dash_vprd_sismed: '26362',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'HIDROCORTISONA (COMO SUCCINATO SÓDICO) 100 MG INY',
      TipoMI: 'M',
      PrecioU: 3.5899,
      consumo: 0,
      stock: 16,
      fila: '47',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400170005',
      swc_dash_vprd_sismed: '03999',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'HIPROMELOSA 3 MG/ML SOL OFT 10 ML',
      TipoMI: 'M',
      PrecioU: 2.16,
      consumo: 73,
      stock: 773,
      fila: '48',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580200430007',
      swc_dash_vprd_sismed: '04024',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'IBUPROFENO 100 MG/5 ML SUS 60 ML',
      TipoMI: 'M',
      PrecioU: 1.03,
      consumo: 0,
      stock: 3,
      fila: '49',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580200430010',
      swc_dash_vprd_sismed: '04034',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'IBUPROFENO 400 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.08,
      consumo: 10,
      stock: 1551,
      fila: '50',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '068001220604',
      swc_dash_vprd_sismed: '',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'JUEGO DE REPUESTOS PARA MANTENIMIENTO DE REFRIGERADORA DE VACUNAS TIPO ICE\n' +
        'LINED 98 L X 4 PIEZAS MODELO VLS304A AC',
      TipoMI: 'O',
      PrecioU: 121.965661,
      consumo: 25.431654,
      stock: 36918,
      fila: '51',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400490004',
      swc_dash_vprd_sismed: '23833',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'KETOTIFENO 10 ML 0.25 MG/ML SOL',
      TipoMI: 'M',
      PrecioU: 21.8099,
      consumo: 3,
      stock: 6,
      fila: '52',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400180001',
      swc_dash_vprd_sismed: '04338',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'LATANOPROST 50 UG/ML SOL OFT 2.5 ML',
      TipoMI: 'M',
      PrecioU: 4.49,
      consumo: 20,
      stock: 1129,
      fila: '53',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580100210021',
      swc_dash_vprd_sismed: '04420',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'LIDOCAINA CLORHIDRATO 2 G/100 G GEL 30 G',
      TipoMI: 'M',
      PrecioU: 4.5599,
      consumo: 0,
      stock: 16,
      fila: '54',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580100210019',
      swc_dash_vprd_sismed: '04390',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'LIDOCAINA CLORHIDRATO SIN PRESERVANTES 2 G/100 ML INY 20 ML',
      TipoMI: 'M',
      PrecioU: 1.59,
      consumo: 2,
      stock: 93,
      fila: '55',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '495700380002',
      swc_dash_vprd_sismed: '16737',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'LLAVE DE TRIPLE VIA DESCARTABLE',
      TipoMI: 'I',
      PrecioU: 0.54,
      consumo: 8,
      stock: 300,
      fila: '56',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583700020003',
      swc_dash_vprd_sismed: '04567',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'MANITOL 20 G/100 ML INY 500 ML',
      TipoMI: 'M',
      PrecioU: 35.2,
      consumo: 2,
      stock: 59,
      fila: '57',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580200440001',
      swc_dash_vprd_sismed: '04677',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'METAMIZOL SODICO 1 G INY 2 ML',
      TipoMI: 'M',
      PrecioU: 0.23,
      consumo: 15,
      stock: 370,
      fila: '58',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583800760002',
      swc_dash_vprd_sismed: '04743',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'METOCLOPRAMIDA CLORHIDRATO 5 MG/ML INY 2 ML',
      TipoMI: 'M',
      PrecioU: 0.93,
      consumo: 0,
      stock: 23,
      fila: '59',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584900300001',
      swc_dash_vprd_sismed: '04831',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'MIDAZOLAM 5 MG INY 5 ML',
      TipoMI: 'M',
      PrecioU: 1.8899,
      consumo: 3,
      stock: 47,
      fila: '60',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584900300007',
      swc_dash_vprd_sismed: '18511',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'MIDAZOLAM 50 MG INY 10 ML',
      TipoMI: 'M',
      PrecioU: 9.55,
      consumo: 0,
      stock: 4,
      fila: '61',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '582600710006',
      swc_dash_vprd_sismed: '04850',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'MITOMICINA 2 MG INY 2 ML',
      TipoMI: 'M',
      PrecioU: 78,
      consumo: 0,
      stock: 6,
      fila: '62',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400430010',
      swc_dash_vprd_sismed: '18062',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'MOXIFLOXACINO 5 ML 5 MG/ML SOL',
      TipoMI: 'M',
      PrecioU: 6,
      consumo: 6,
      stock: 174,
      fila: '63',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400020006',
      swc_dash_vprd_sismed: '04951',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'NAFAZOLINA 1 MG/ML SOL OFT 15 ML',
      TipoMI: 'M',
      PrecioU: 4.91,
      consumo: 3,
      stock: 50,
      fila: '64',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '586700010001',
      swc_dash_vprd_sismed: '05009',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'NEOSTIGMINA METILSULFATO 500 µG/ML INY 1 ML',
      TipoMI: 'M',
      PrecioU: 0.99,
      consumo: 0,
      stock: 47,
      fila: '65',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583800710002',
      swc_dash_vprd_sismed: '35040',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'OMEPRAZOL, 20 MG -  TABLETA LIBERACION MODIFICADA',
      TipoMI: 'M',
      PrecioU: 0.06,
      consumo: 0,
      stock: 30,
      fila: '66',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580200460006',
      swc_dash_vprd_sismed: '05309',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PARACETAMOL 120 MG/5 ML JBE  60 ML',
      TipoMI: 'M',
      PrecioU: 2.4599,
      consumo: 0,
      stock: 1,
      fila: '67',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580200460011',
      swc_dash_vprd_sismed: '05335',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PARACETAMOL 500 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.05,
      consumo: 92,
      stock: 1129,
      fila: '68',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400620001',
      swc_dash_vprd_sismed: '05431',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PILOCARPINA CLORHIDRATO 10 ML 20 MG/ML SOL',
      TipoMI: 'M',
      PrecioU: 16.0399,
      consumo: 0,
      stock: 60,
      fila: '69',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '585100090002',
      swc_dash_vprd_sismed: '05551',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'POTASIO CLORURO 20 G/100 ML INY 10 ML',
      TipoMI: 'M',
      PrecioU: 0.22,
      consumo: 0,
      stock: 1,
      fila: '70',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400690003',
      swc_dash_vprd_sismed: '05578',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PREDNISOLONA 10 MG/ML SUS OFT 5 ML',
      TipoMI: 'M',
      PrecioU: 3.23,
      consumo: 16,
      stock: 404,
      fila: '71',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '587100070009',
      swc_dash_vprd_sismed: '05588',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PREDNISONA 20 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.1,
      consumo: 7,
      stock: 818,
      fila: '72',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '587100070003',
      swc_dash_vprd_sismed: '05590',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PREDNISONA 50 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.18,
      consumo: 35,
      stock: 497,
      fila: '73',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580100080004',
      swc_dash_vprd_sismed: '05626',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PROPOFOL 10 MG/ML INY 20 ML',
      TipoMI: 'M',
      PrecioU: 5.3799,
      consumo: 1,
      stock: 30,
      fila: '74',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400240006',
      swc_dash_vprd_sismed: '05638',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'PROXIMETACAINA 5 MG/ML  SOL OFT 15 ML',
      TipoMI: 'M',
      PrecioU: 28.96,
      consumo: 4,
      stock: 19,
      fila: '75',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583800720003',
      swc_dash_vprd_sismed: '05658',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'RANITIDINA 25 MG/ML INY 2 ML',
      TipoMI: 'M',
      PrecioU: 0.33,
      consumo: 0,
      stock: 7,
      fila: '76',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583800720002',
      swc_dash_vprd_sismed: '05661',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'RANITIDINA 300 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.28,
      consumo: 0,
      stock: 77,
      fila: '77',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '',
      swc_dash_vprd_sismed: '24709',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'RETINOL ACETATO  50000 UI  ',
      TipoMI: 'M',
      PrecioU: 0.4,
      consumo: 0,
      stock: 1000,
      fila: '78',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '580100010001',
      swc_dash_vprd_sismed: '05809',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SEVOFLURANO 100 ML/100 ML SOL 250 ML',
      TipoMI: 'M',
      PrecioU: 199.11,
      consumo: 0,
      stock: 15,
      fila: '79',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '585100120003',
      swc_dash_vprd_sismed: '05856',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SODIO BICARBONATO 8.4 G/100 ML INY 20 ML',
      TipoMI: 'M',
      PrecioU: 0.76,
      consumo: 0,
      stock: 2,
      fila: '80',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '585100100008',
      swc_dash_vprd_sismed: '05889',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SODIO CLORURO 20 G/100 ML INY 20 ML',
      TipoMI: 'M',
      PrecioU: 1.09,
      consumo: 0,
      stock: 2,
      fila: '81',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '585100100011',
      swc_dash_vprd_sismed: '05873',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SODIO CLORURO 900 MG/100 ML INY 1 L',
      TipoMI: 'M',
      PrecioU: 2.5,
      consumo: 1,
      stock: 66,
      fila: '82',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '585100100002',
      swc_dash_vprd_sismed: '05872',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SODIO CLORURO 900 MG/100 ML INY 100 ML',
      TipoMI: 'M',
      PrecioU: 0.99,
      consumo: 9,
      stock: 913,
      fila: '83',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '585100100005',
      swc_dash_vprd_sismed: '05880',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SODIO CLORURO 900 MG/100 ML INY 250 ML',
      TipoMI: 'M',
      PrecioU: 1.6399,
      consumo: 0,
      stock: 100,
      fila: '84',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400430027',
      swc_dash_vprd_sismed: '19152',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SOLUCION SALINA BALANCEADA 500 ML SOL',
      TipoMI: 'M',
      PrecioU: 33.5,
      consumo: 2,
      stock: 145,
      fila: '85',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '581300030009',
      swc_dash_vprd_sismed: '05986',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SULFAMETOXAZOL + TRIMETOPRIMA 200 MG + 40 MG/5 ML SUS 60 ML',
      TipoMI: 'M',
      PrecioU: 1.2,
      consumo: 0,
      stock: 1,
      fila: '86',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '581300030005',
      swc_dash_vprd_sismed: '03515',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'SULFAMETOXAZOL + TRIMETOPRIMA 800 MG + 160 MG TAB',
      TipoMI: 'M',
      PrecioU: 0.15,
      consumo: 0,
      stock: 841,
      fila: '87',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400610001',
      swc_dash_vprd_sismed: '06111',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'TETRACICLINA CLORHIDRATO 1 G/100 G UNG OFT 6 G',
      TipoMI: 'M',
      PrecioU: 10.69,
      consumo: 2,
      stock: 179,
      fila: '88',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '584400630002',
      swc_dash_vprd_sismed: '06144',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'TIMOLOL MALEATO 5 MG/ML SOL OFT 5 ML',
      TipoMI: 'M',
      PrecioU: 2.66,
      consumo: 30,
      stock: 324,
      fila: '89',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '587000070002',
      swc_dash_vprd_sismed: '06228',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'TOXINA BOTULINICA TIPO A 100 UI INY',
      TipoMI: 'M',
      PrecioU: 470.87,
      consumo: 2,
      stock: 4,
      fila: '90',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '586900060010',
      swc_dash_vprd_sismed: '06232',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'TRAMADOL 50 MG INY 2 ML',
      TipoMI: 'M',
      PrecioU: 0.37,
      consumo: 1,
      stock: 739,
      fila: '91',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '587100060002',
      swc_dash_vprd_sismed: '06284',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'TRIAMCINOLONA ACETONIDO 40 MG INY 1 ML',
      TipoMI: 'M',
      PrecioU: 9.3399,
      consumo: 0,
      stock: 16,
      fila: '92',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583400060001',
      swc_dash_vprd_sismed: '06357',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'TROPICAMIDA 10 MG/ML SOL OFT 15 ML',
      TipoMI: 'M',
      PrecioU: 33.6099,
      consumo: 2,
      stock: 11,
      fila: '93',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '581500090001',
      swc_dash_vprd_sismed: '06471',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'VANCOMICINA CLORHIDRATO 500 MG INY',
      TipoMI: 'M',
      PrecioU: 3.16,
      consumo: 0,
      stock: 35,
      fila: '94',
      totalFilas: 95,
      totalPaginas: 1
    },
    {
      swc_dash_vprd_siga: '583600190038',
      swc_dash_vprd_sismed: '06517',
      AutoridadSanitaria: 'ESSALUD',
      alm_codigo: 94339,
      Establecimiento: 'INSTITUTO PERUANO DE OFTALMOLOGIA',
      FechaReporte: '2023-04-17',
      swc_dash_vprd_descripcion: 'YODO POVIDONA 10 G/100 ML SOL 1 L',
      TipoMI: 'M',
      PrecioU: 16.9699,
      consumo: 0,
      stock: 10,
      fila: '95',
      totalFilas: 95,
      totalPaginas: 1
    }
  ]

  constructor(private location: Location) {
    addIcons({ chevronForward })
  }

  ngOnInit() {
  }

  back(): void {
    this.location.back();
  }

}
